"""Brematic integration for Home Assistant"""

VERSION = "0.6.0"

CONF_SYSTEM_CODE = "system_code"
CONF_GATEWAY_TYPE = "gateway_type"
CONF_UNIT_CODE = "unit_code"
CONF_UNIT_TYPE = "unit_type"

GATEWAY_TYPE_BRENNENSTUHL = "Brennenstuhl"
GATEWAY_TYPE_INTERTECHNO = "Intertechno"
GATEWAY_TYPE_CONNAIR = "ConnAir"
GATEWAY_TYPES = [GATEWAY_TYPE_BRENNENSTUHL, GATEWAY_TYPE_INTERTECHNO, GATEWAY_TYPE_CONNAIR]

UNIT_TYPE_RCS1000N = "RCS1000N"
UNIT_TYPE_RCR1000N = "RCR1000N"
UNIT_TYPE_AB440SA = "AB440SA"
UNIT_TYPE_CMR300 = "CMR300"
UNIT_TYPE_CMR500 = "CMR500"
UNIT_TYPE_CMR1000 = "CMR1000"
UNIT_TYPE_ITR300 = "ITR300"
UNIT_TYPE_ITR3500 = "ITR3500"
UNIT_TYPE_PAR1500 = "PAR1500"
UNIT_TYPES = [
    UNIT_TYPE_RCS1000N,  # Brennenstuhl
    UNIT_TYPE_RCR1000N,  # Brennenstuhl
    UNIT_TYPE_AB440SA,   # Elro
    UNIT_TYPE_CMR300,    # Intertechno
    UNIT_TYPE_CMR500,    # Intertechno
    UNIT_TYPE_CMR1000,   # Intertechno
    UNIT_TYPE_ITR300,    # Intertechno
    UNIT_TYPE_ITR3500,   # Intertechno
    UNIT_TYPE_PAR1500,   # Intertechno
]

DEFAULT_UNIT_TYPE = UNIT_TYPE_RCS1000N
DEFAULT_GATEWAY_TYPE = GATEWAY_TYPE_BRENNENSTUHL
